### ISSUE TITLE
Init fails to setup a GIT environment if there already exists a previous 'slurm-scripts' folder

### ISSUE THREAD

**Issue by TorecLuik** [NL-BioImaging/biomero#11]
If you supply a Git repo like in the .ini below, it fails to `init` Slurm (if you already have a slurm-scripts from a previous `init`).

Error:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/opt/omero/server/omero/tmp/omero_omero-server/163/process180jzxtr.dir/./script", line 132, in <module>
    runScript()
  File "/opt/omero/server/omero/tmp/omero_omero-server/163/process180jzxtr.dir/./script", line 62, in runScript
    slurmClient.setup_job_scripts()
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 499, in setup_job_scripts
    r = self.run_commands([cmd], env)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 793, in run_commands
    result = self.run(cmd, env=env, **kwargs)  # out_stream=out_stream,
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 23, in opens
    return method(self, *args, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 763, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/invoke/context.py", line 113, in _run
    return runner.run(command, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/runners.py", line 75, in run
    return super().run(command, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/invoke/runners.py", line 395, in run
    return self._run_body(command, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/invoke/runners.py", line 451, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/invoke/runners.py", line 518, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'git clone "$REPOSRC" "$LOCALREPO" 2> /dev/null || git -C "$LOCALREPO" pull'

Exit code: 128

Stdout: already printed

Stderr: already printed
```

Error(s) if your run it locally:
```
sh-4.4# git clone "$REPOSRC" "$LOCALREPO" 2> /dev/null || git -C "$LOCALREPO" pull
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sh-4.4# git clone "$REPOSRC" "$LOCALREPO"                                         
fatal: destination path '/data/my-scratch/slurm-scripts' already exists and is not an empty directory.
```

Reproducible config:
```
[SSH]
# -------------------------------------
# SSH settings
# -------------------------------------
# The alias for the SLURM SSH connection
host=localslurm
# Set the rest of your SSH configuration in your SSH config under this host name/alias
# Or in e.g. /etc/fabric.yml (see Fabric's documentation for details on config loading)

[SLURM]
# -------------------------------------
# Slurm settings
# -------------------------------------
# General settings for where to find things on the Slurm cluster.
# -------------------------------------
# PATHS
# -------------------------------------
# The path on SLURM entrypoint for storing datafiles
#
# Note: 
# This example is relative to the Slurm user's home dir
slurm_data_path=/data/my-scratch/data
# The path on SLURM entrypoint for storing container image files
#
# Note: 
# This example is relative to the Slurm user's home dir
slurm_images_path=/data/my-scratch/singularity_images/workflows
# The path on SLURM entrypoint for storing the slurm job scripts
#
# Note: 
# This example is relative to the Slurm user's home dir
slurm_script_path=/data/my-scratch/slurm-scripts
# -------------------------------------
# REPOSITORIES
# -------------------------------------
# A (github) repository to pull the slurm scripts from.
#
# Note: 
# If you provide no repository, we will generate scripts instead!
# Based on the job_template and the descriptor.json
#
# Example:
#slurm_script_repo=https://github.com/TorecLuik/slurm-scripts
slurm_script_repo=https://github.com/SafarbatiSami/slurm-scripts/

# -------------------------------------
# Processing settings
# -------------------------------------
# General/default settings for processing jobs.
# Note: NOT YET IMPLEMENTED
# Note: If you need to change it for a specific case only,
# you should change the job script instead, either in Omero or Slurm 


[MODELS]
# -------------------------------------
# Model settings
# -------------------------------------
# Settings for models/singularity images that we want to run on Slurm
#
# NOTE: keys have to be unique, and require a <key>_repo and <key>_image value as well.
#
# NOTE 2: Versions for the repo are highly encouraged! 
# Latest/master can change and cause issues with reproducability!
# We pickup the container version based on the version of the repository.
# For generic master branch, we pick up generic latest container.
# -------------------------------------
# CELLPOSE SEGMENTATION
# -------------------------------------
# The path to store the container on the slurm_images_path
cellpose=cellpose
# The (e.g. github) repository with the descriptor.json file
cellpose_repo=https://github.com/TorecLuik/W_NucleiSegmentation-Cellpose/tree/v1.2.9
# The jobscript in the 'slurm_script_repo'
cellpose_job=jobs/cellpose.sh
# Override the default job values for this workflow
# Or add a job value to this workflow
# For more examples of such parameters, google SBATCH parameters.
# If you don't want to override, comment out / delete the line.
# Run CellPose Slurm with 10 GB GPU
# cellpose_job_gres=gpu:1g.10gb:1
# Run CellPose Slurm with 15 GB CPU memory
# cellpose_job_mem=15GB
# -------------------------------------
# # STARDIST SEGMENTATION
# # -------------------------------------
# # The path to store the container on the slurm_images_path
# stardist=stardist
# # The (e.g. github) repository with the descriptor.json file
# stardist_repo=https://github.com/Neubias-WG5/W_NucleiSegmentation-Stardist/tree/v1.3.2
# # The jobscript in the 'slurm_script_repo'
# stardist_job=jobs/stardist.sh
# -------------------------------------
# CELLPROFILER SEGMENTATION
# # -------------------------------------
# # The path to store the container on the slurm_images_path
# cellprofiler=cellprofiler
# # The (e.g. github) repository with the descriptor.json file
# cellprofiler_repo=https://github.com/Neubias-WG5/W_NucleiSegmentation-CellProfiler/tree/v1.6.4
# # The jobscript in the 'slurm_script_repo'
# cellprofiler_job=jobs/cellprofiler.sh
# -------------------------------------
# DEEPCELL SEGMENTATION
# # -------------------------------------
# # The path to store the container on the slurm_images_path
# deepcell=deepcell
# # The (e.g. github) repository with the descriptor.json file
# deepcell_repo=https://github.com/Neubias-WG5/W_NucleiSegmentation-DeepCell/tree/v.1.4.3
# # The jobscript in the 'slurm_script_repo'
# deepcell_job=jobs/deepcell.sh
# -------------------------------------
# IMAGEJ SEGMENTATION
# # -------------------------------------
# # The path to store the container on the slurm_images_path
# imagej=imagej
# # The (e.g. github) repository with the descriptor.json file
# imagej_repo=https://github.com/Neubias-WG5/W_NucleiSegmentation-ImageJ/tree/v1.12.10
# # The jobscript in the 'slurm_script_repo'
# imagej_job=jobs/imagej.sh
# # -------------------------------------
# # CELLPROFILER SPOT COUNTING
# # -------------------------------------
# The path to store the container on the slurm_images_path
cellprofiler_spot=cellprofiler_spot
# The (e.g. github) repository with the descriptor.json file
cellprofiler_spot_repo=https://github.com/TorecLuik/W_SpotCounting-CellProfiler/tree/v1.0.1
# The jobscript in the 'slurm_script_repo'
cellprofiler_spot_job=jobs/cellprofiler_spot.sh
# # -------------------------------------
# CELLEXPANSION
# -------------------------------------
# The path to store the container on the slurm_images_path
cellexpansion=cellexpansion
# The (e.g. github) repository with the descriptor.json file
cellexpansion_repo=https://github.com/TorecLuik/W_CellExpansion/tree/v2.0.1
# The jobscript in the 'slurm_script_repo'
cellexpansion_job=jobs/cellexpansion.sh
# # -------------------------------------
# SPOT COUNTING
# -------------------------------------
# The path to store the container on the slurm_images_path
spotcounting=spotcounting
# The (e.g. github) repository with the descriptor.json file
spotcounting_repo=https://github.com/TorecLuik/W_CountMaskOverlap/tree/v1.0.1
# The jobscript in the 'slurm_script_repo'
spotcounting_job=jobs/spotcounting.sh
 
# -------------------------------------
#                BIOM3D
# -------------------------------------
# The path to store the container on the slurm_images_path
biom3d=biom3d
# The (e.g. github) repository with the descriptor.json file
biom3d_repo=https://github.com/SafarbatiSami/W_Biom3d-Workflow-Omero/tree/v1.0.0
# The jobscript in the 'slurm_script_repo'
biom3d_job=jobs/biom3d.sh
 
```

**Comment by TorecLuik** [comment]
Going to just remove the folder first and then clone. The current 'or pull' version doesn't work in this scenario.

**Comment by TorecLuik** [comment]
Pushed to master

**Comment by TorecLuik** [comment]
ok, let's close after we release instead ;)
