### ISSUE TITLE
Slurm Workflow - Failed to get results

### ISSUE THREAD

**Issue by TorecLuik** [NL-BioImaging/biomero#8]
![image](https://github.com/NL-BioImaging/biomero/assets/68958516/d9eb9a4c-6289-441b-9364-514552674708)

There is a timeout when the job takes too long on Slurm

**Comment by TorecLuik** [comment]
`2024-02-22 17:07:54,736 DEBUG [                                __main__] [542] (MainThread) Job 247811 is busy...
2024-02-22 17:07:54,740 DEBUG [                           omero.gateway] [542] (MainThread) Traceback (most recent call last):
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/omero/gateway/__init__.py", line 1885, in keepAlive
    return self.c.sf.keepAlive(self._proxies['admin']._getObj())
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/omero/gateway/__init__.py", line 5039, in _getObj
    self._ping()
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/omero/gateway/__init__.py", line 5053, in _ping
    if not self._conn.c.sf.keepAlive(self._obj):
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/omero_API_ice.py", line 1312, in keepAlive
    return _M_omero.api.ServiceFactory._op_keepAlive.invoke(self, ((proxy, ), _ctx))
omero.SessionTimeoutException: exception ::omero::SessionTimeoutException`
